### ISSUE TITLE
Address example?

### ISSUE THREAD

**Issue by bcackerman** [nozpheratu/agilecrm-wrapper#15]
Hi,

Do you have an example of how to add an address to a customer?

just adding `address: "123 St", city: "Chicago"` into `AgileCRMWrapper::Contact.create()` doesn't seem to be doing it.

**Comment by nozpheratu** [comment]
@bcackerman Most of this sort of this information is handled either as "custom" or "system" attributes by Agile. All these attributes can be accessed via the properties hash, here's what that looks like:

``` ruby
contact = AgileCRMWrapper::Contact.create(
  email: 'test@example.com',
  city: 'Chicago',
  address: '123 St'
)
contact.properties
=> [{"type"=>"SYSTEM", "name"=>"email", "subtype"=>"", "value"=>"test@example.com"},
{"type"=>"CUSTOM", "name"=>"city", "value"=>"Chicago"},
{"type"=>"SYSTEM", "name"=>"address", "value"=>"123 St"}]
```

It's a little difficult to work with this hash directly so this library also includes a `get_property` method on the contact class. If you know the name of the custom/system property you're looking for just run it through this method to get what you need:

``` ruby
contact.get_property('email')
=> 'test@example.com'
contact.get_property('city')
=> 'Chicago'
contact.get_property('address')
=> '123 St'
```
