### ISSUE TITLE
If property type has more than 1 value causes error

### ISSUE THREAD

**Issue by pjohn** [nozpheratu/agilecrm-wrapper#4]
For example, if a contact has 3 phone numbers the system will generate the following error on the call

contact.get_property("phone")
ArgumentError: wrong number of arguments (3 for 0..1)
	from /Users/pjohn/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/ostruct.rb:87:in `initialize'
	from /Users/pjohn/.rvm/gems/ruby-2.1.5/gems/agilecrm-wrapper-1.0.1/lib/agilecrm-wrapper/contact.rb:102:in `new'
	from /Users/pjohn/.rvm/gems/ruby-2.1.5/gems/agilecrm-wrapper-1.0.1/lib/agilecrm-wrapper/contact.rb:102:in `get_property'

Also, applies for email property

**Comment by nozpheratu** [comment]
@pjohn Must have missed an edge case somewhere. Thanks for sharing, I'll look into this over the weekend.

**Comment by nozpheratu** [comment]
@pjohn Just put out a fix. Try pulling directly from the github repo and let me know if that solves it for you.

**Comment by pjohn** [comment]
@nozpheratu - Works great.  Thanks!
